global:
    scrape_interval: 15s

scrape_configs:
    - job_name: Frontend
      static_configs:
          - targets: ["frontend:80"]

    - job_name: 'backend'
      static_configs:
          - targets: ['backend:443']
      scheme: https
      tls_config:
        insecure_skip_verify: true

    - job_name: Database
      static_configs:
          - targets: ["database:5432"]


rule_files:
  - alert_rules.yml