global:
    scrape_interval: 15s

scrape_configs:

    - job_name: 'backend'
      static_configs:
          - targets: ['backend:443']
      scheme: https
      tls_config:
        insecure_skip_verify: true

rule_files:
  - alert_rules.yml