import React, { useEffect, useRef } from "react";
import img from "../../Home/CodeQr.png";
import "./Popup.css";

export function PopupSetup2Fa(props) {


  useEffect(() => {

    //send a post methode to the server and wait for Code Qr to render it 



  }, [])




  const setPopUp = props.update;
  return (
    <div className="popUpContainer">
      <div className="popUp">
        <svg
          onClick={() => setPopUp(false)}
          className="close-popup"
          width="20"
          height="20"
          viewBox="0 0 26 26"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M16.0807 13L25.3668 3.71137C26.2111 2.86695 26.2111 1.47774 25.3668 0.633316C24.5227 -0.211105 23.1338 -0.211105 22.2896 0.633316L13.0034 9.92195L3.7172 0.633316C2.873 -0.211105 1.48416 -0.211105 0.639958 0.633316C0.217858 1.05553 0 1.61393 0 2.17234C0 2.73075 0.217858 3.28916 0.639958 3.71137L9.92616 13L0.639958 22.2886C0.217858 22.7108 0 23.2693 0 23.8277C0 24.3861 0.217858 24.9445 0.639958 25.3667C1.48416 26.2111 2.873 26.2111 3.7172 25.3667L13.0034 16.0781L22.2896 25.3667C23.1338 26.2111 24.5227 26.2111 25.3668 25.3667C26.2111 24.5223 26.2111 23.1331 25.3668 22.2886L16.0807 13Z"
            fill="white"
            fillOpacity="0.29"
          />
        </svg>
        <h1>Tow Factor Authentication Setup</h1>
        <h2>1. Install Google Authenticator App</h2>
        <h2>2. Open the App and Scan the Qr Code </h2>
        <img src={img} alt="" />
        <h2>3. Click the button to finish setup</h2>
        <button onClick={() => setPopUp(false)}>ok</button>
      </div>
    </div>
  );
}

export function PopupEnternumber(props) {
  
  const setPopUp = props.update;
  const res = useRef(null);
  
  function sendNumber(){

    const numbers = res.current;

    console.log(numbers.value);


    // send Get request to the backend and send user name and digit in query string




    setPopUp(false); 
  }
  
  
  return (
    <>
      <div className="popUpContainer">
        <div className="popUp">
          <svg
            onClick={() => setPopUp(false)}
            className="close-popup"
            width="20"
            height="20"
            viewBox="0 0 26 26"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M16.0807 13L25.3668 3.71137C26.2111 2.86695 26.2111 1.47774 25.3668 0.633316C24.5227 -0.211105 23.1338 -0.211105 22.2896 0.633316L13.0034 9.92195L3.7172 0.633316C2.873 -0.211105 1.48416 -0.211105 0.639958 0.633316C0.217858 1.05553 0 1.61393 0 2.17234C0 2.73075 0.217858 3.28916 0.639958 3.71137L9.92616 13L0.639958 22.2886C0.217858 22.7108 0 23.2693 0 23.8277C0 24.3861 0.217858 24.9445 0.639958 25.3667C1.48416 26.2111 2.873 26.2111 3.7172 25.3667L13.0034 16.0781L22.2896 25.3667C23.1338 26.2111 24.5227 26.2111 25.3668 25.3667C26.2111 24.5223 26.2111 23.1331 25.3668 22.2886L16.0807 13Z"
              fill="white"
              fillOpacity="0.29"
            />
          </svg>
          <h1>Tow-Factor Authentication</h1>
          <h2>Enter the Code generated by your Authenticator App</h2>
          <input ref={res} type="text" />
          <button onClick={() => {sendNumber() }}>verify</button>
        </div>
      </div>
    </>
  );
}
