# Generated by Django 4.2.9 on 2024-03-23 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User_Management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="friend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="status",
            field=models.CharField(
                choices=[
                    ("F", "friend"),
                    ("B", "blocked"),
                    ("BY", "blocked you"),
                    ("W", "wait_for_accept"),
                    ("I", "invited"),
                ],
                max_length=2,
            ),
        ),
    ]
