# Generated by Django 4.2.9 on 2024-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_Management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
