# Generated by Django 5.0.2 on 2024-02-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0002_alter_info_banner_img_alter_info_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2FA_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='qrcode_2FA',
            field=models.FilePathField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_code_2FA',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='uri_2FA',
            field=models.URLField(blank=True),
        ),
    ]
