# Generated by Django 4.2.9 on 2024-05-08 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User_Management", "0002_notification_is_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="notifier",
        ),
        migrations.AddField(
            model_name="notification",
            name="sended_to",
            field=models.ManyToManyField(
                related_name="notifications", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
