# Generated by Django 4.2.9 on 2024-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "User_Management",
            "0003_remove_notification_notifier_notification_sended_to_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("js", models.JSONField()),
            ],
        ),
    ]
