# Generated by Django 4.2.9 on 2024-05-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Game", "0004_alter_acheivement_users"),
        (
            "User_Management",
            "0003_remove_notification_notifier_notification_sended_to_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="info",
            name="grade_id",
        ),
        migrations.AddField(
            model_name="info",
            name="grade",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Game.grade"
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="level",
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name="info",
            name="wallet",
            field=models.IntegerField(default=500),
        ),
    ]
