# Generated by Django 4.2.9 on 2024-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "User_Management",
            "0004_remove_info_grade_id_info_grade_alter_info_level_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("C", "Chat"),
                    ("F", "Friendship"),
                    ("G", "Game"),
                    ("T", "Tournament"),
                ],
                max_length=20,
            ),
        ),
    ]
