# Generated by Django 4.2.9 on 2024-05-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_Management", "0005_alter_notification_content_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
