# Generated by Django 4.2.9 on 2024-05-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User_Management", "0008_remove_notification_is_hidden_user_is_42_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="info",
            name="banner_img",
        ),
        migrations.RemoveField(
            model_name="info",
            name="gender",
        ),
    ]
