# Generated by Django 4.2.9 on 2024-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_Management", "0009_remove_info_banner_img_remove_info_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_multicast",
            field=models.BooleanField(default=False),
        ),
    ]
