# Generated by Django 5.0.3 on 2024-06-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_Management", "0010_notification_is_multicast"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="tournament_win",
            field=models.IntegerField(default=0),
        ),
    ]
