# Generated by Django 4.2.13 on 2024-06-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0011_info_tournament_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='level',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='info',
            name='profile_img',
            field=models.ImageField(blank=True, default='default/default.png', upload_to='images'),
        ),
    ]
