# Generated by Django 4.2.13 on 2024-06-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0012_alter_info_level_alter_info_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile_img',
            field=models.ImageField(blank=True, default='default/default.png', upload_to='static/images'),
        ),
    ]
