# Generated by Django 4.2.9 on 2024-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tournament", "0002_tournament_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="schedule",
            field=models.JSONField(null=True),
        ),
    ]
