# Generated by Django 4.2.9 on 2024-05-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tournament", "0003_alter_tournament_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="match_index",
            field=models.IntegerField(default=0),
        ),
    ]
