# Generated by Django 4.2.9 on 2024-05-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tournament", "0004_tournament_match_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="schedule",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
