# Generated by Django 4.2.9 on 2024-06-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tournament", "0005_alter_tournament_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="isStarted",
            field=models.BooleanField(default=False),
        ),
    ]
