# Generated by Django 4.2.9 on 2024-06-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Tournament", "0007_alter_tournament_creator_alter_tournament_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Tournament.participant",
            ),
        ),
    ]
