# Generated by Django 4.2.9 on 2024-04-19 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Game", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
