# Generated by Django 5.0.2 on 2024-02-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
