# Generated by Django 4.2.9 on 2024-05-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Game", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="current_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="in_use",
                to="Game.item",
            ),
        ),
    ]
