# Generated by Django 4.2.9 on 2024-05-14 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Game", "0003_alter_items_current_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acheivement",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="acheivements", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
