# Generated by Django 4.2.9 on 2024-05-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Game", "0004_alter_acheivement_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="enemy_match",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Game.match",
            ),
        ),
    ]
