# Generated by Django 4.2.9 on 2024-05-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Tournament", "0005_alter_tournament_schedule"),
        ("Game", "0005_alter_match_enemy_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Tournament.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="enemy_match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Game.match",
            ),
        ),
    ]
