# Generated by Django 4.2.13 on 2024-06-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_match_is_played_alter_match_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acheivement',
            name='icon_path',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='acheivement',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='color',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_path',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='padel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
