# Generated by Django 4.2.13 on 2024-06-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_alter_acheivement_icon_path_alter_acheivement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acheivement',
            name='icon_path',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_path',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
